FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD Projeto3.jar /opt/Projeto3/
EXPOSE 8080
WORKDIR /opt/Projeto3/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "Projeto3.jar"]
